### ISSUE TITLE
License not defined

### ISSUE THREAD

**Issue by RainerWinkler** [karvla/covid19count#1]
Hi Mr. Larrson,
I just forked your repository to make semilogarithmic plots. It worked well and fast. Thank you.
But you added no license to your repository. So I do not know in which way I am allowed to use your coding.
Can I use your coding? Are there any restrictions?
Thank you,
Rainer Winkler

**Comment by karvla** [comment]
Thanks for reminding me. Do whatever you want and good luck!:)

**Comment by RainerWinkler** [comment]
Hi Mr. Larrson, thank you! With best wishes, Rainer Winkler
