### ISSUE TITLE
Please add MIT license to repository

### ISSUE THREAD

**Issue by RainerWinkler** [karvla/covid19count#3]
Dear Mr Larsson,
your project is very helpfull and I need a lot of adaption. In issue #1 you replied "Do whatever you want and good luck!:)". I interpretate this as MIT license (https://choosealicense.com/ "A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.")

Following https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository and the Github License Chooser https://choosealicense.com/ I propose you add the MIT license to your repository.

I am then able to copy it in a new repository (not a forked one). In this new repository I will state that it is based on code from your repository.

Is this OK for you?

Thank you very much,
Rainer Winkler

**Comment by karvla** [comment]
Hello! I added the MIT licence in response to your first issue. You can definitely start a new cloned repository. I'm exited to see what you come up with! Good luck!

**Comment by RainerWinkler** [comment]
Hello! Thank you. And I am excited to see how easy it is to use your coding. Thank you!
