### ISSUE TITLE
Method to access Excel file has to change

### ISSUE THREAD

**Issue by RainerWinkler** [karvla/covid19count#4]
I changed the logic to access the Excel file. It appears that the website changed.
I do it currently the following (not elegant) way:
    #Changed method to find Excel file URL
    xls_url = ""
    for link in soup.find_all('a'):
        url2 = link.get('href')
        if type(url2) == str:
            if url2.find(".xls") != -1:
                if xls_url == "":
                    xls_url = url2
    
    #xls_link_box = soup.find(text="Download today's data: Geographic distribution of COVID-19 cases worldwide - XLS file")
    #xls_url = xls_link_box.parent["href"]

Please check

**Comment by karvla** [comment]
Thank you so much for letting me know! I solved i using regex:
`xls_link_box = soup.find("a", href=re.compile(".+\.x    ls"))`
`xls_url = xls_link_box["href"]`
